[package]
name = "voxy_render"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
webgl = ["wgpu/webgl"]
openxr = ["dep:openxr"]

[dependencies]
half = "2.7.1"
bytemuck = { version = "1.25.2", features = ["derive"] }
glam = { version = "0.33.6", features = ["bytemuck"] }
gltf = { version = "1.4.1", default-features = false, features = ["utils", "names"] }
openxr = { version = "0.22.0", default-features = false, optional = true }
raw-window-handle = "0.6.2"
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg", "hdr"] }
voxy_animation = { path = "../voxy_animation" }
voxy_core = { path = "../voxy_core" }
voxy_lighting = { path = "../voxy_lighting" }
voxy_mesher = { path = "../voxy_mesher" }
wgpu = { version = "30.0.1", features = ["noop"] }

[dev-dependencies]
voxy_editor = { path = "../voxy_editor" }
physics = { path = "../physics" }
physics_voxel = { path = "../physics_voxel" }
voxy_world = { path = "../voxy_world" }
voxy_text = { path = "../voxy_text" }
voxy_ui_winit = { path = "../voxy_ui_winit" }
voxy_ui = { path = "../voxy_ui" }
voxy_assets = { path = "../voxy_assets" }
winit = "0.30.13"
voxy_scene = { path = "../voxy_scene" }
pollster = "1.0.1"

[lints]
workspace = true
