[package]
name = "voxy_render"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bytemuck = { version = "1.25.2", features = ["derive"] }
glam = { version = "0.33.6", features = ["bytemuck"] }
voxy_animation = { path = "../voxy_animation" }
voxy_core = { path = "../voxy_core" }
voxy_lighting = { path = "../voxy_lighting" }
voxy_mesher = { path = "../voxy_mesher" }
wgpu = { version = "30.0.1", features = ["noop"] }

[dev-dependencies]
pollster = "1.0.1"

[lints]
workspace = true
