[package]
name = "voxy_web"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
physics = { path = "../physics" }
physics_voxel = { path = "../physics_voxel" }
voxy_runtime = { path = "../voxy_runtime" }
voxy_mesher = { path = "../voxy_mesher" }
glam = "0.33.6"
voxy_gpu = { path = "../voxy_gpu" }
voxy_world = { path = "../voxy_world" }
voxy_core = { path = "../voxy_core" }
js-sys = "0.3.104"
voxy_render = { path = "../voxy_render", features = ["webgl"] }
wgpu = { version = "30.0.1", features = ["webgl"] }
wasm-bindgen = "0.2.127"
wasm-bindgen-futures = "0.4.77"
web-sys = { version = "0.3.104", features = ["HtmlCanvasElement", "Window"] }

[lints]
workspace = true
