#!/usr/bin/env python3
"""Render manually authored source-review notes against pinned evidence."""
import hashlib,html,json,pathlib,re
ROOT=pathlib.Path(__file__).resolve().parents[2]
OUT=ROOT/'docs/hardware-research';CACHE=ROOT/'target/hardware-research/sources'
def esc(s):return html.escape(str(s),quote=True)
reviews=[]
for line in (OUT/'reviews.tsv').read_text().splitlines():
 name,index,note=line.split('|',2);d=CACHE/name.replace('/','__');r=json.loads((d/'record.json').read_text());f=r['files'][int(index)]
 assert re.fullmatch('[0-9a-f]{40}',r['commit'])
 assert hashlib.sha256((d/f['local']).read_bytes()).hexdigest()==f['sha256']
 files=[{k:v for k,v in x.items() if k!='excerpts'} for x in r['files']]
 reviews.append(dict(repository=name,commit=r['commit'],review_scope='selected_source_sections',reviewed_file=f['path'],source_url=f['url'],finding=note,files=files,cache_directory=str(d.relative_to(ROOT)),tree_truncated=r.get('tree_truncated',False)))
assert len(reviews)==100 and len({r['repository'].lower() for r in reviews})==100
(OUT/'reviewed-inventory.json').write_text(json.dumps(dict(date='2026-10-02',repositories=reviews,scope='100 targeted source reviews; not whole-repository audits; foreign code not executed'),ensure_ascii=False,indent=2)+'\n')
rows=''.join(f'<tr><td>{i+1}</td><td><a href="{esc(r["source_url"])}">{esc(r["repository"])}</a><small>{esc(r["reviewed_file"])}<br>commit {r["commit"][:12]}</small></td><td>{esc(r["finding"])}</td></tr>' for i,r in enumerate(reviews))
page='''<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Voxy — 100 репозиториев: GPU, shaders, CUDA</title>
<style>body{font:16px/1.55 system-ui,sans-serif;color:#182436;background:#f5f7fa;margin:0}main{max-width:1180px;margin:auto;padding:36px 24px}h1{font-size:32px;line-height:1.2}h2{margin-top:36px}a{color:#1456b8}small{display:block;color:#566579;font-size:12px;overflow-wrap:anywhere}p,li{max-width:980px}.summary{background:#e7effb;padding:18px 24px;border-left:4px solid #1456b8}.limit{color:#566579}table{border-collapse:collapse;background:white;width:100%;font-size:14px}th,td{padding:12px;text-align:left;border-bottom:1px solid #dce3ed;vertical-align:top}th{position:sticky;top:0;background:#e7effb}td:nth-child(2){width:32%}input{font:inherit;width:calc(100% - 26px);padding:12px;border:1px solid #bac8dc;border-radius:6px;margin:12px 0}#count{font-size:14px;color:#566579}</style>
<main><h1>Как делают аппаратные пути: 100 репозиториев</h1><p class="limit">Обзор от 2 октября 2026. Движки, графические библиотеки, компиляторы, SDK и примеры. Это 100 обзоров выбранных участков исходников, а не аудит всего кода каждого проекта. Подробно прослежены ключевые пути: dependency graph, завершение submission, readback, allocation budget, compute → indirect draw, device recovery и CUDA interop. Чужой код не собирался и не запускался.</p>
<div class="summary"><strong>Вывод для Voxy</strong><p>Следующий большой шаг — связать уже существующие GPU-модули управлением ресурсами и очередями: общий учёт памяти, ограниченный пул readback, явная передача compute-результата renderer и безопасное повторное использование после завершения GPU. CUDA следует развивать как отдельный аппаратный путь с проверкой устройства и синхронизации.</p></div>
<h2>Что подтверждают исходники</h2>
<ol><li><strong>Проходы описывают доступ к данным.</strong> Godot выводит барьеры из usage и write dependencies; Blender учитывает используемые buffers при перестановке команд. В Voxy нужен общий контракт producer/consumer проходов. Внутри wgpu часть tracking уже реализована: дублировать её вручную не следует.</li>
<li><strong>Ресурсы освобождают по завершению работы.</strong> wgpu LifetimeTracker, Flax deferred deletion, DirectXTK12 pending pages и Filament command pools отделяют CPU ownership от GPU completion. Счётчик кадров сам по себе недостаточен для межочередного interop.</li>
<li><strong>Readback — отдельный, ограниченный поток.</strong> Bevy держит requested/mapped очереди и возвращает буфер в pool после результата; melonJS учитывает row alignment. Для Voxy полезно оставить nonblocking API и добавить reuse/backpressure.</li>
<li><strong>Compute может кормить renderer без копирования на CPU.</strong> bgfx показывает culling → compaction → indirect draw; The Forge переводит particle buffers между UAV и indirect/shader states; three.js поддерживает indirect compute dispatch.</li>
<li><strong>Бюджет — не только размер пользовательских данных.</strong> VMA и D3D12MA различают allocations, heap/block usage и доступный бюджет; gpu-allocator различает allocated bytes и block capacity. В бюджет Voxy должны попасть staging, scratch, history, geometry и сохранённые в RAM чанки.</li>
<li><strong>Recovery восстанавливает зависимые объекты.</strong> PixiJS пересоздаёт свой device и рассылает contextChange, но не присваивает себе recovery чужого shared device. Urho3D убирает потерянную surface из FBO caches.</li></ol>
<p class="limit">Эти выводы — интерпретация просмотренных участков. Конкретные файлы и закреплённые commits находятся в таблице ниже. Mirrors Unity перекрываются с Unity Graphics: 100 репозиториев не означает 100 независимых архитектур. Старые примеры и archived проекты учитываются как инженерные примеры, а не как актуальные рекомендации зависимостей.</p>
<h2>Что говорят форумы и где проверено правило</h2>
<ul><li><a href="https://gamedev.net/forums/topic/609639-cpu-and-gpu-synchronization/">GameDev.net: CPU/GPU synchronization</a> — ring buffers и несколько кадров в обработке; объяснение 2011 года относится к API того времени. Для современных lifetime правил использован <a href="https://github.khronos.org/Vulkan-Site/tutorial/latest/Synchronization/Frame_in_Flight/03_resource_lifetimes.html">Khronos: Resource Lifetimes</a>.</li>
<li><a href="https://gamedev.net/forums/topic/675184-shader-permutations/">GameDev.net: Shader Permutations</a> — варианты зависят от mesh, material и pass; обсуждение автора OGRE. Для Voxy ключ pipeline следует описывать полными свойствами, а не одним непроверяемым hash.</li>
<li><a href="https://community.khronos.org/t/compute-shader-imagestore-load-synchronization/106516">Khronos Forum: voxel counting и workgroup synchronization</a> — barrier внутри dispatch не создаёт глобальный порядок между workgroups. Для отдельных проходов проверены <a href="https://github.com/KhronosGroup/Vulkan-Docs/wiki/Synchronization-Examples">официальные примеры synchronization</a>. Это особенно важно при распараллеливании ordered water solver.</li>
<li><a href="https://forum.godotengine.org/t/draw-compute-shader-as-texture/104081">Godot Forum: compute texture → экран</a> — показан конфликт local/main RenderingDevice и лишний readback; часть предложенного native-handle sharing на форуме не является универсально проверенным решением. В <a href="https://docs.godotengine.org/en/stable/tutorials/shaders/compute_shaders.html">официальном compute tutorial</a> немедленный sync выделен как блокирующий учебный путь.</li>
<li><a href="https://forums.developer.nvidia.com/t/cudawaitexternalsemaphoresasync-blocks-cpu-kernel-launch/329028">NVIDIA Forum: wait-before-signal deadlock</a> — обсуждение ограничения external semaphore imports. <a href="https://docs.nvidia.com/cuda/cuda-programming-guide/04-special-topics/graphics-interop.html">CUDA Programming Guide</a> подтверждает необходимость matching device UUID, корректных mappings и порядка signals/waits. Правила Vulkan timeline нельзя автоматически переносить на CUDA imports.</li>
<li><a href="https://community.khronos.org/t/memory-and-texture-barriers-in-opengl/110637">Khronos Forum: memory/texture barriers</a> — различает incoherent writes и feedback при render-to-texture. Нельзя вставлять одинаковый универсальный barrier для всех backend.</li></ul>
<h2>Приоритеты для Voxy</h2>
<table><thead><tr><th>Шаг</th><th>Изменение</th><th>Критерий завершения</th></tr></thead><tbody>
<tr><td>1</td><td>Общий memory admission и accounting: loaded/retained chunks, GPU storage, readback, transient scratch. payload_bytes остаётся логическим размером, не RSS.</td><td>Отказ до allocation; лимит на in-flight bytes; ошибка/отмена/device loss не возвращают память в reuse до безопасного completion.</td></tr>
<tr><td>2</td><td>Пул readback buffers с ownership lease и bounded queue. ComputeJob::encode_snapshot сейчас создаёт отдельный staging buffer.</td><td>Повторное использование только после unmap и completion; stale results не публикуются; отмена не делает ещё используемый буфер свободным.</td></tr>
<tr><td>3</td><td>Общий compute → render контракт и GPU-resident путь. Разделить steps, публикацию render view и диагностический CPU snapshot.</td><td>Работающая сцена без обязательного полного readback; измерены CPU/GPU времена, объём копий и steady-state allocations.</td></tr>
<tr><td>4</td><td>CUDA interop: сохранить уже существующие UUID/LUID проверки, исследовать persistent imports и external semaphore handoff вместо повторного import/synchronize в publish.</td><td>Физическая NVIDIA; Vulkan и DX12 отдельно; несколько кадров, ошибки, shutdown и несовпадающие устройства. Текущий blocking путь сохраняется до проверки нового.</td></tr>
<tr><td>5</td><td>Capability profiles и shader/pipeline artifacts: реальные features/limits/formats, стадии, layouts, precision policy, options и target. Warmup отдельно от rendering.</td><td>Неподдерживаемая комбинация отвергается или выбирает проверенный путь; failed compile сохраняет предыдущий рабочий pipeline.</td></tr>
<tr><td>6</td><td>Реальное recovery renderer + world state; затем platform acceptance на desktop/mobile/XR.</td><td>После device loss сохранены edits и pending-work semantics, ресурсы созданы заново; физические устройства подтверждают поддержку.</td></tr>
</tbody></table>
<p>Базовые места в текущем Voxy проверены чтением исходников: ComputeJob::encode_snapshot и ComputeDispatch::copy_buffer создают staging; VulkanGravityInterop::publish проверяет ownership и использует import/release/synchronize/acquire; Vulkan UUID и DX12 LUID checks уже есть. Эти рекомендации не утверждают отсутствия всех механизмов и не являются результатами performance benchmark.</p>
<h2>100 обзоров исходников</h2><label for="filter">Поиск по проекту, файлу или подходу</label><input id="filter" placeholder="Например: readback, fence, CUDA, WebGPU"><p id="count">100 / 100</p><table id="sources"><thead><tr><th>№</th><th>Репозиторий и просмотренный файл</th><th>Наблюдение и применимость</th></tr></thead><tbody>ROWS</tbody></table>
<p class="limit">Закреплённые commits, SHA-256 полученных файлов, scope и локальные cache paths записаны в reviewed-inventory.json. Полные полученные файлы лежат в игнорируемом target/hardware-research/sources; таблица содержит пересказ, не копии чужого исходного кода. Наличие файла в cache не означает, что весь файл или весь репозиторий проверен.</p></main>
<script>const input=document.getElementById('filter');const rows=[...document.querySelectorAll('#sources tbody tr')];input.addEventListener('input',()=>{const q=input.value.toLocaleLowerCase();let n=0;for(const row of rows){row.hidden=!row.textContent.toLocaleLowerCase().includes(q);if(!row.hidden)n++}document.getElementById('count').textContent=`${n} / ${rows.length}`});</script></html>'''.replace('ROWS',rows)
(OUT/'report.html').write_text(page)
print('PASS: 100 unique source reviews; pinned commits and selected file hashes verified')
