// Hardware Indirect Voxel Render Shader
// Consumes GpuVoxelVertex directly generated by GPU Compute mesher
// and renders using GPU DrawIndirectArgs with zero CPU readback overhead.

struct Camera {
    view_proj: mat4x4<f32>,
};

@group(0) @binding(0) var<uniform> camera: Camera;
@group(1) @binding(0) var materials: texture_2d_array<f32>;
@group(1) @binding(1) var material_sampler: sampler;

struct VoxelVertexInput {
    @location(0) position: vec3<f32>,
    @location(1) face_dir: u32,
    @location(2) material: u32,
    @location(3) ao: u32,
    @location(4) uv: vec2<f32>,
};

struct VertexOutput {
    @builtin(position) position: vec4<f32>,
    @location(0) uv: vec2<f32>,
    @location(1) @interpolate(flat) material: u32,
    @location(2) normal: vec3<f32>,
    @location(3) ao: f32,
    @location(4) @interpolate(flat) light: vec2<f32>,
};

fn face_normal(face: u32) -> vec3<f32> {
    switch face {
        case 0u: { return vec3<f32>(-1.0, 0.0, 0.0); }
        case 1u: { return vec3<f32>( 1.0, 0.0, 0.0); }
        case 2u: { return vec3<f32>(0.0, -1.0, 0.0); }
        case 3u: { return vec3<f32>(0.0,  1.0, 0.0); }
        case 4u: { return vec3<f32>(0.0, 0.0, -1.0); }
        default: { return vec3<f32>(0.0, 0.0, 1.0); }
    }
}

@vertex
fn vs_main(input: VoxelVertexInput) -> VertexOutput {
    var output: VertexOutput;
    output.position = camera.view_proj * vec4<f32>(input.position, 1.0);
    output.uv = input.uv;
    output.material = input.material;
    output.normal = face_normal(input.face_dir);
    output.ao = clamp(f32(input.ao) / 3.0, 0.0, 1.0);
    output.light = vec2<f32>(1.0, 0.0);
    return output;
}

@fragment
fn fs_main(input: VertexOutput) -> @location(0) vec4<f32> {
    let albedo = textureSample(materials, material_sampler, input.uv, i32(input.material));
    let sun = normalize(vec3<f32>(0.45, 0.82, 0.35));
    let diffuse = 0.18 + 0.82 * max(dot(input.normal, sun), 0.0);
    let illumination = max(0.08, max(input.light.y, input.light.x * diffuse));
    let source = dot(albedo.rgb, vec3<f32>(0.299, 0.587, 0.114))
        * illumination * mix(0.58, 1.0, input.ao);

    let level = floor(clamp(source, 0.0, 0.999) * 32.0) / 31.0;
    let lcd_paper = vec3<f32>(0.78, 0.78, 0.76);
    let lcd_ink = vec3<f32>(0.035, 0.035, 0.035);
    let color = mix(lcd_ink, lcd_paper, level);
    return vec4<f32>(color, albedo.a);
}
