[package]
name = "voxy_gameplay"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
voxy_assets = { path = "../voxy_assets" }
voxy_audio = { path = "../voxy_audio" }
voxy_scene = { path = "../voxy_scene" }
voxy_input = { path = "../voxy_input" }
voxy_ui = { path = "../voxy_ui" }
voxy_text = { path = "../voxy_text" }
physics = { path = "../physics" }
glam = "0.33.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lints]
workspace = true

[dev-dependencies]
voxy_audio_device = { path = "../voxy_audio_device" }

[[bench]]
name = "angular_motion"
harness = false
