[package]
name = "voxy_xr"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
voxy_ui = { path = "../voxy_ui" }
openxr = { version = "0.22.0", default-features = false, features = ["loaded"] }

[target.'cfg(target_os = "android")'.dependencies]
android-activity = { version = "0.6.1", features = ["native-activity"] }

[lints.rust]
unsafe_code = "deny"
missing_debug_implementations = "warn"
[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
