[package]
name = "voxy_vulkan"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = []
cuda = ["dep:voxy_cuda", "voxy_cuda/cuda"]

[target.'cfg(any(target_os = "linux", target_os = "windows"))'.dependencies]
voxy_cuda = { path = "../voxy_cuda", optional = true }
ash = "0.38.0"
wgpu = "30.0.1"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62", features = ["Win32_Graphics_Direct3D12", "Win32_Graphics_Dxgi_Common", "Win32_Security"] }

[lints.rust]
unsafe_code = "deny"
missing_debug_implementations = "warn"
[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[target.'cfg(any(target_os = "linux", target_os = "windows"))'.dev-dependencies]
voxy_gpu = { path = "../voxy_gpu" }
voxy_render = { path = "../voxy_render" }
pollster = "1.0.1"
winit = "0.30.13"

[[example]]
name = "cuda_gravity_render"
required-features = ["cuda"]

[[example]]
name = "cuda_gravity_window"
required-features = ["cuda"]
