[package]
name = "voxy_streamline"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = []
native = []
wgpu-dx12 = ["native", "dep:wgpu", "dep:windows"]
render-policy = ["dep:voxy_render"]
scene-dx12 = ["wgpu-dx12", "render-policy"]

[dependencies]
glam = "0.33.6"
voxy_render = { path = "../voxy_render", optional = true }
wgpu = { version = "30.0.1", optional = true, default-features = false, features = ["std", "dx12"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", optional = true, features = ["Win32_Graphics_Direct3D12", "Win32_Graphics_Direct3D", "Win32_Graphics_Dxgi", "Win32_Graphics_Dxgi_Common"] }

[dev-dependencies]
pollster = "1.0.1"
half = "2.7.1"

[build-dependencies]
cc = "1.4.4"

[lints.rust]
unsafe_code = "deny"
missing_debug_implementations = "warn"
[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
